[package]
name = "fast-magic"
version = "0.1.0"
authors = ["bedlam"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magic = "*"
regex = "*"
num_cpus = "*"
walkdir = "*"
clap = "*"